### ISSUE TITLE
[Question] Where could I find the design doc for haha

### ISSUE THREAD

**Issue by fvdcx** [square/haha#23]
Hi @pyricau , Where could I find the design doc for haha?
There were not many comments in source code, which is a little difficult for a beginner to read

**Comment by pyricau** [comment]
There is no design doc. See https://github.com/square/haha#haha-204 => HAHA is just a repackaging of perflib, which I think has roots it jhat. The code could be cleaned up and commented, but because it's just a repackaging that would have to be done in AOSP directly.

The easiest way to figure out how to use it is probably to look at how it's used in LeakCanary: https://github.com/square/leakcanary/blob/master/leakcanary-analyzer/src/main/java/com/squareup/leakcanary/HeapAnalyzer.java
